"""
InterviewSession SQLAlchemy model — Day 3

Represents a single interview session linking one candidate to one job.
Stores the Gemini-generated questions and the candidate's recorded answers.

Constraints:
  - One session per candidate per job (unique_constraint on candidate_id + job_id)
"""

import uuid
from datetime import datetime, timezone

from sqlalchemy import Column, DateTime, Float, ForeignKey, UniqueConstraint
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import relationship

from app.database import Base


class InterviewSession(Base):
    __tablename__ = "interview_sessions"

    __table_args__ = (
        UniqueConstraint("candidate_id", "job_id", name="uq_interview_session_candidate_job"),
    )

    id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        nullable=False,
    )
    candidate_id = Column(
        UUID(as_uuid=True),
        ForeignKey("candidates.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    job_id = Column(
        UUID(as_uuid=True),
        ForeignKey("jobs.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Questions generated by Gemini: list of {id, type, question, time_limit_seconds}
    questions = Column(
        JSONB,
        nullable=False,
        comment="List of question dicts generated by Gemini",
    )

    # Answers recorded by candidate: list of {question_id, transcript, video_url}
    answers = Column(
        JSONB,
        nullable=False,
        default=list,
        comment="List of {question_id, transcript, video_url}",
    )

    started_at = Column(DateTime(timezone=True), nullable=True)
    completed_at = Column(DateTime(timezone=True), nullable=True, default=None)

    # Scoring columns added in Day 4 Phase 2
    answer_scores = Column(
        JSONB,
        nullable=True,
        comment="List of {question_id, relevance, depth, communication, feedback, red_flag}",
    )
    overall_interview_score = Column(
        Float,
        nullable=True,
        comment="Mean of per-answer (relevance+depth+communication)/3 scores",
    )
    scorecard = Column(
        JSONB,
        nullable=True,
        comment="Gemini-generated holistic scorecard dict",
    )

    # Relationships
    candidate = relationship("Candidate", back_populates="interview_session")

    def __repr__(self) -> str:
        return (
            f"<InterviewSession id={self.id} candidate_id={self.candidate_id} "
            f"job_id={self.job_id}>"
        )
