"""add_interview_token_to_candidates

Revision ID: 6ec1faa768c1
Revises: f99aed89af76
Create Date: 2026-06-25 15:16:24.619795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ec1faa768c1'
down_revision: Union[str, Sequence[str], None] = 'f99aed89af76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('interview_token', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'candidates', ['interview_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidates', type_='unique')
    op.drop_column('candidates', 'interview_token')
    # ### end Alembic commands ###
