"""add_token_expiry_and_invite_fields

Revision ID: e2a0b1c3d4e5
Revises: fa5c4e7a82aa
Create Date: 2026-06-26 14:48:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2a0b1c3d4e5'
down_revision: Union[str, Sequence[str], None] = 'fa5c4e7a82aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('interview_token_created_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'interview_token_created_at')
    # ### end Alembic commands ###
