"""initial_schema

Revision ID: f99aed89af76
Revises: 
Create Date: 2026-06-25 13:05:34.096088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f99aed89af76'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('required_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='List of {name: str, seniority: junior|mid|senior|lead|any}'),
    sa.Column('preferred_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='List of strings'),
    sa.Column('experience_range', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='{min: int, max: int} years'),
    sa.Column('role_level', sa.String(length=20), nullable=True, comment='junior | mid | senior | lead'),
    sa.Column('implicit_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Non-obvious requirements extracted from JD text'),
    sa.Column('shortlist_threshold', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('current_title', sa.String(length=255), nullable=True),
    sa.Column('current_company', sa.String(length=255), nullable=True),
    sa.Column('listed_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='List of skill strings'),
    sa.Column('experience_summary', sa.Text(), nullable=True),
    sa.Column('work_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='List of {title, company, duration_months}'),
    sa.Column('source', sa.String(length=50), nullable=False, comment='linkedin | indeed | manual'),
    sa.Column('profile_url', sa.String(length=1024), nullable=True),
    sa.Column('confidence_level', sa.String(length=10), nullable=False, comment='high | medium | low'),
    sa.Column('shortlisted', sa.Boolean(), nullable=False),
    sa.Column('shortlist_override', sa.Boolean(), nullable=False),
    sa.Column('interview_status', sa.String(length=20), nullable=False, comment='not_invited | invited | in_progress | completed'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_job_id'), 'candidates', ['job_id'], unique=False)
    op.create_table('scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('technical_score', sa.Float(), nullable=False),
    sa.Column('seniority_score', sa.Float(), nullable=False),
    sa.Column('domain_score', sa.Float(), nullable=False),
    sa.Column('skills_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Dict of skill_name -> cosine_similarity float'),
    sa.Column('red_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='List of {type: str, description: str}'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scores_candidate_id'), 'scores', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_scores_job_id'), 'scores', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scores_job_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_candidate_id'), table_name='scores')
    op.drop_table('scores')
    op.drop_index(op.f('ix_candidates_job_id'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_table('jobs')
    # ### end Alembic commands ###
