"""add_scoring_columns_to_interview_session

Revision ID: fa5c4e7a82aa
Revises: 09748931f560
Create Date: 2026-06-26 13:24:05.907601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa5c4e7a82aa'
down_revision: Union[str, Sequence[str], None] = '09748931f560'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('answer_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='List of {question_id, relevance, depth, communication, feedback, red_flag}'))
    op.add_column('interview_sessions', sa.Column('overall_interview_score', sa.Float(), nullable=True, comment='Mean of per-answer (relevance+depth+communication)/3 scores'))
    op.add_column('interview_sessions', sa.Column('scorecard', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Gemini-generated holistic scorecard dict'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'scorecard')
    op.drop_column('interview_sessions', 'overall_interview_score')
    op.drop_column('interview_sessions', 'answer_scores')
    # ### end Alembic commands ###
